{
  "version": 1,
  "status": "fail",
  "message": "\rLeap year not divisible by 4 in common year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                                          \n  Expected: <false>\n    Actual: <true>\n  \n  package:test_api                      expect\n  test/example_all_fail_test.dart 10:7  main.<fn>.<fn>\n  \n\r\u001b[1m\u001b[1;30mloading test/example_all_fail_test.dart\u001b[0m\u001b[0m                                                                                                                                                   \nConsider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'.\n\rLeap year divisible by 4, not divisible by 100 in leap year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                          \n  Expected: <true>\n    Actual: <false>\n  \n  package:test_api                      expect\n  test/example_all_fail_test.dart 15:7  main.<fn>.<fn>\n  \n\r\u001b[1m\u001b[1;30mloading test/example_all_fail_test.dart\u001b[0m\u001b[0m                                                                                                                                                   \nConsider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'.\n\r\u001b[31mSome tests failed.\u001b[0m                                                                                                                                                                        "
}
