{
  "version": 1,
  "status": "fail",
  "message": "\rLeap year divisible by 400 in leap year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                                          \n  Expected: <true>\n    Actual: <false>\n  \n  package:matcher                           expect\n  test/example_partial_fail_test.dart 40:7  main.<fn>.<fn>\n  \n\n\u001b[1m\u001b[36mTo run this test again:\u001b[0m dart test test/example_partial_fail_test.dart -p vm --plain-name 'Leap year divisible by 400 in leap year'\n\rLeap year divisible by 400 but not by 125 is still a leap year \u001b[1m\u001b[31m[E]\u001b[0m\u001b[0m                                                                                   \n  Expected: <true>\n    Actual: <false>\n  \n  package:matcher                           expect\n  test/example_partial_fail_test.dart 45:7  main.<fn>.<fn>\n  \n\n\u001b[1m\u001b[36mTo run this test again:\u001b[0m dart test test/example_partial_fail_test.dart -p vm --plain-name 'Leap year divisible by 400 but not by 125 is still a leap year'\n\r\u001b[31mSome tests failed.\u001b[0m                                                                                                                                                                        \n\nConsider enabling the flag chain-stack-traces to receive more detailed exceptions.\nFor example, 'dart test --chain-stack-traces'."
}
